language: node_js
node_js:
  - "8"
os:
  -linux
script:
  - npm run docs
  - npm run test
#  - npm run lint
deploy:
  provider: pages
  local_dir: node_docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
